version: '3.8'
services:
  # WolfShop Application
  wolfshop-app:
    build:
      context: ./
      dockerfile: scripts/Dockerfile
    container_name: wolfshop-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APACHE_LOG_DIR=/var/log/apache2
    depends_on:
      - wolfshop-mysql
    networks:
      - wolfshop-net
  # WolfShop Database
  wolfshop-mysql:
    image: mysql:8.0
    container_name: wolfshop-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wolf_shop
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wolfshop-net

networks:
  wolfshop-net: