services:
  # WolfShop Application
  wolfshop-app:
    build:
      context: ./
      dockerfile: scripts/startup/Dockerfile
    container_name: wolfshop-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APACHE_LOG_DIR=/var/log/apache2
    depends_on:
      - wolfshop-mysql-test
    networks:
      - wolfshop-net-test

  # WolfShop Test Database
  wolfshop-mysql-test:
    image: mysql:8.0
    container_name: wolfshop-mysql-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wolf_shop_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_data_test:/var/lib/mysql
    networks:
      - wolfshop-net-test

networks:
  wolfshop-net-test: